apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: releasesets.helmfile.helm.sh
spec:
  group: helmfile.helm.sh
  versions:
    - name: v1alpha1
      served: true
      storage: true
  names:
    kind: ReleaseSet
    plural: releasesets
    singular: releaseset
  scope: Namespaced
